### ISSUE TITLE
add column "user_creation_data" for users model

### ISSUE THREAD

**Issue by shy-tan** [shy-tan/humble-kanban#7]
maybe we can add another column "user_creation_data" which might show when the user started being part of the application?

_Originally posted by @Angrypenguin1995 in https://github.com/shy-tan/humble-kanban/pull/5#discussion_r975979408_

**Comment by szjanecki** [comment]
I think you mean `user_creation_date` ;) And sure, good idea. Not sure if there is a need to create issues for such stuff though. Especially when there is a ticket in progress for this thing. And even if, please use Trello for them. No need to use 2 ticketing systems ;)

**Comment by shy-tan** [comment]
> Especially when there is a ticket in progress for this thing. 

`user_creation_date` was not there in the original schema diagram we made, how do you propose we track **new ideas or features**?

**Comment by szjanecki** [comment]
If the feature is in progress, propose it to us via discord (or inside PR, you can just ping us on discord it is something we need to discuss), and if we agree add a comment on trello issue it regards. If it's something not related to the feature you are working on, then create new ticket on Trello for that.

**Comment by shy-tan** [comment]
[d37e35b](https://github.com/shy-tan/humble-kanban/pull/5/commits/d37e35b1c5f694fdefab71f25e6a3c94f50ce062) fixes this.
